### ISSUE TITLE
Support 243.* IDE version

### ISSUE THREAD

**Issue by ris58h** [YunaBraska/github-workflow-plugin#72]
After upgrading IntelliJ to 2024.3 I've got `Incompatible: requires IDE build 242.* or earlier` error.

**Comment by codemedic** [comment]
@YunaBraska Thanks for your hard work in creating this plugin.
Any chance you could take a look at this issue.

**Comment by YunaBraska** [comment]
Ah sorry, I haven’t been actively monitoring GitHub issues, but I will address the version incompatibility
The plugin is currently in maintenance mode, as I am just alone and IntelliJ has integrated some of its functionalities, and the lack of automated testing for key features makes further development impractical. But this issue seems manageable to fix. Thanks a lot for reminding me and your patience!

**Comment by YunaBraska** [comment]
@codemedic release `2024.3.0` is publishing :)
